CREATE TABLE auth_providers
(
    id               UUID                        NOT NULL,
    user_id          UUID                        NOT NULL,
    provider         VARCHAR(50)                 NOT NULL,
    provider_user_id VARCHAR(100)                NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_auth_providers PRIMARY KEY (id)
);

CREATE TABLE prefixes
(
    prefix_id    BIGINT                      NOT NULL,
    prefix       VARCHAR(20)                 NOT NULL,
    user_id      UUID                        NOT NULL,
    reserved_for VARCHAR(100)                NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_prefixes PRIMARY KEY (prefix_id)
);

CREATE TABLE tiny_links
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tiny_code       VARCHAR(20)                             NOT NULL,
    redirection_url TEXT                                    NOT NULL,
    user_id         UUID,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_active       BOOLEAN                                 NOT NULL,
    deactivated_at  TIMESTAMP WITHOUT TIME ZONE,
    is_custom       BOOLEAN                                 NOT NULL,
    code_type       VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_tiny_links PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id UUID NOT NULL,
    roles   VARCHAR(20)
);

CREATE TABLE users
(
    user_id                UUID                        NOT NULL,
    email_id               VARCHAR(255)                NOT NULL,
    name                   VARCHAR(100)                NOT NULL,
    username               VARCHAR(50)                 NOT NULL,
    password               VARCHAR(100)                NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_type              VARCHAR(20)                 NOT NULL,
    registration_completed BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE prefixes
    ADD CONSTRAINT uc_0c56bd67e9d3afb567745f70b UNIQUE (prefix);

ALTER TABLE tiny_links
    ADD CONSTRAINT uc_tiny_links_tinycode UNIQUE (tiny_code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_emailid UNIQUE (email_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE auth_providers
    ADD CONSTRAINT FK_AUTH_PROVIDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE prefixes
    ADD CONSTRAINT FK_PREFIXES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE tiny_links
    ADD CONSTRAINT FK_TINY_LINKS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);